version: "3"
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile  
    volumes:
      - ./wordpress/:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/conf.ini
    container_name: wc_wordpress
    depends_on:
      - wc_db
  nginx:
    image: nginx:latest
    container_name: wc_server
    volumes:
      - ./wordpress/:/var/www/html
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
      - ./etc/letsencrypt:/etc/nginx/ssl
    ports:
      - 81:80
      # - 443:443
    depends_on:
      - wordpress
  # certbot:
  #   image: certbot/certbot
  #   depends_on:
  #     - nginx
  #   container_name: wc_certbot
  #   volumes:
  #     - ./etc/letsencrypt:/etc/letsencrypt
  #     - ./wordpress/:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email aleksander.freelancer@gmail.com --agree-tos --no-eff-email -d legal-services.site
  wc_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: wc_db
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8082:80"
    environment:
      PMA_HOST: wc_db
    container_name: wc_admin
